apiVersion: v1
kind: Secret
metadata:
  name: np-repo-cred
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
# stringData: # for accessing manifests in private repos
#   type: git
#   url: https://github.com:Thegaijin/iac-k8s-argocd.git
#   password: thisisatest
#   username: kumusops
