apiVersion: v1
kind: Secret
metadata:
  name: helm-configs-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:kumusoft/iac-k8s-argocd
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    <private key details>
    -----END OPENSSH PRIVATE KEY-----
